### ISSUE TITLE
Question: is the HealthProtect supported?

### ISSUE THREAD

**Issue by redoz** [mathiastornblom/net.tornbloms.blueair#1]
Hi, 
I see the driver in the source, but I don't see it when I installed the app on my Homey Pro (2023)? Is this something destined for the next release or am I doing something wrong? If there's anything I can do to contribute/test please let me know.

**Comment by mathiastornblom** [comment]
I'm sorry for not getting back to you sooner. I have initiated the HelhProtect as I want to support it, but I dont have a device to test it against. I guess you do. What model? Can you run a few postman commands to check for me?

**Comment by redoz** [comment]
No problem, it's been quite busy here as well, I have the 7770i, I've written a few drivers for Homey already so I'm fairly familiar with it so I can probably do better than just run a few postman commands if you'd like. But tell me what you need and I'll try to provide.

**Comment by mathiastornblom** [comment]
Go a GET https://api-eu-west-1.blueair.io/v2/user/{your username}/login/ with the following Herades
X-API-KEY-TOKEN eyJhbGciOiJIUzI1NiJ9.eyJncmFudGVlIjoiYmx1ZWFpciIsImlhdCI6MTQ1MzEyNTYzMiwidmFsaWRpdHkiOi0xLCJqdGkiOiJkNmY3OGE0Yi1iMWNkLTRkZDgtOTA2Yi1kN2JkNzM0MTQ2NzQiLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwicXVvdGEiOi0xLCJyYXRlTGltaXQiOi0xfQ.CJsfWVzFKKDDA6rWdh-hjVVVE9S3d6Hu9BzXG9htWFw
Authorization Basic {Base64 encoded usernamne and password in the format username:password}
In the response header X-AUTH-TOKEN this will need to be added together with the X-API-KEY-TOKEN for further requests

Do you get an output of a request to GET https://api-eu-west-1.blueair.io/v2/owner/{your username}/device/
dont forget the headers above

**Comment by redoz** [comment]
Is username supposed to be my email address?

**Comment by mathiastornblom** [comment]
Yes, the credentials you use when you log in to your app on your phone.

**Comment by redoz** [comment]
It returns a 200 with a body `false`, tried this a few different ways but that's all I get back from the login endpoint

**Comment by mathiastornblom** [comment]
That would indicate the username and/or password is wrong.
![image](https://github.com/mathiastornblom/net.tornbloms.blueair/assets/15749388/99cacbdb-8c29-4137-b902-8b3b29e8667b)
Does it look something similar?

**Comment by redoz** [comment]
Yeah, I tried to create the header manually, and using the Authentication tab in Postman (I also tried using powershell).
My password _does_ have a colon in it, but that _shouldn't_ be an issue, unless they did something stupid, and I can login using the app (I signed out and in to verify).

I can try changing the password to something else and see if that works.

**Comment by mathiastornblom** [comment]
HealthProtect is now supported. you can test by adding /test to the end of the Homey App Store  to test this before it goes public
